export const ConstantList = {
  ENTER_KEY: "Enter",
};
export enum SELECT_OPTION {
  SELECT_ACTION = "select-option",
  CLEAR_ACTION = "clear",
  REMOVE_ACTION = "remove-value",
}

export const PERMISSIONS = {
  MODULE :"MODULE",
  AUTHORITY: "AUTHORITY",
  ROLE: "ROLE",
  USER: "USER",
  RECEIPT: "RECEIPT",
  CART : "CART",
  SUPPLIER: "SUPPLIER",
  FAVOURITE : "FAVOURITE",
  PRODUCT : "PRODUCT",
  CATEGORY : "CATEGORY",
  COLOR :"COLOR",
  SIZE :"SIZE",
  CUSTOMER:"CUSTOMER",
  PAYMENT :"PAYMENT-METHOD",
  PROMOTION:"PROMOTION",
  ORDER : "ORDER",
  REPORT :"REPORT"
}

export const PERMISSION_ABILITY = {
  VIEW: "VIEW",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  UPLOAD: "UPLOAD",
  EXPORT: "EXPORT"
}

export const MODULE = {
  MANAGE : "MANAGE" 
}

export const ROLE = {
  USER: "ROLE_USER",
  ADMIN :"ROLE_ADMIN",
  MANAGER:"ROLE_MANAGER",
  ROLE_SUPPER_ADMIN :"ROLE_SUPPER_ADMIN",
  ROLE_ANALYST :"ROLE_ANALYST"
}

export const LOCAL_STORAGE_KEY ={
  AUTHORITIES : "AUTHORITIES",
  USER_TOKEN: "USER_TOKEN",
  USER_ROLE : "USER_ROLE",
  LIST_MENU : "LIST_MENU"
}
