export const ORDER_MANAGER_TAB ={
    CHUA_THANH_TOAN :"CHUA_THANH_TOAN",
    CHO_XU_LY :"CHO_XU_LY",
    DANG_CHUAN_BI_HANG :"DANG_CHUAN_BI_HANG",
    DANG_GIAO :"DANG_GIAO",
    GIAO_HANG_THANH_CONG :"GIAO_HANG_THANH_CONG",
    BI_HUY :"BI_HUY",
}